# Generated by Django 4.1.7 on 2023-03-31 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpicture',
            name='blog_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpicture', to='blog.subtext'),
        ),
        migrations.AlterField(
            model_name='subtext',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subtext', to='blog.blog'),
        ),
    ]
