# Generated by Django 4.1.7 on 2023-04-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_subtext_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtext',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtext', to='blog.blog'),
        ),
    ]
